
var Config = {
  APP_NAME: "Diploma Ilmi LMS",
  PREFIX: {
    MAHASISWA: "DI",
    STAFF: "DI",
    SERTIFIKAT: "DI.SRFT",
    TRANSAKSI: "KEU",
    PENGUMUMAN: "KES"
  },
  SHEET_NAMES: {
    USERS_MAHASISWA: "USERS_MAHASISWA",
    USERS_STAFF: "USERS_STAFF",
    AKADEMIK_MK: "AKADEMIK_MK",
    AKADEMIK_JADWAL: "AKADEMIK_JADWAL",
    AKADEMIK_PRESENSI: "AKADEMIK_PRESENSI",
    AKADEMIK_NILAI: "AKADEMIK_NILAI",
    KEUANGAN_TRANSAKSI: "KEUANGAN_TRANSAKSI",
    KEUANGAN_PENGAJUAN: "KEUANGAN_PENGAJUAN",
    KESISWAAN_SERTIFIKAT: "KESISWAAN_SERTIFIKAT",
    LMS_BANK_SOAL: "LMS_BANK_SOAL",
    LMS_JAWABAN: "LMS_JAWABAN",
    GENERAL_PENGUMUMAN: "GENERAL_PENGUMUMAN"
  },
  FOLDER_NAME: "LMS_UPLOADS",
  CACHE_DURATION: 1500 // 25 minutes in seconds
};

if (typeof module !== 'undefined') module.exports = Config;
